# Pipeline for blockmap

image: quay.io/sheogorath/build-ah-engine:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - package

package:
  stage: package
  image: quay.io/sheogorath/build-ah-engine:latest
  variables:
    LANG: C.UTF-8
  before_script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - podman build --pull -f Dockerfile -t "$CI_REGISTRY_IMAGE" .
    - podman push "$CI_REGISTRY_IMAGE"
  only:
    - master
